spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ticket-service
              uri: lb://ticket-service
              predicates:
                - Path=/api/v1/tickets/**
            - id: trip-service
              uri: lb://trip-service
              predicates:
                - Path=/api/v1/trips/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
